### ISSUE TITLE
prometheus integration server does not return complate data

### ISSUE THREAD

**Issue by javadch** [glaciation-heu/trade-off-service#7]
Data does not cover the current timespan, 
See the attached document.

[Evaluation of data in Prometheus.docx](https://github.com/user-attachments/files/19231448/Evaluation.of.data.in.Prometheus.docx)

**Comment by parklize** [comment]
Hi @a-zharinov, 

As mentioned yesterday's meeting, from UC2 workload, the demanded resource annotations available are currently as follows. 
In case we need more, let us know with instructions regarding how to add additional resource annotations.

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: uc2-workload-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: uc2-workload
    app.kubernetes.io/version: 0.1.26
    helm.sh/chart: uc2-workload-0.1.26
  name: uc2-workload-service
  namespace: uc2
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: >-
                ghcr.io/glaciation-heu/glaciation-uc2-workload-service:0.1.26-4a61598b
              imagePullPolicy: IfNotPresent
              name: uc2-workload
              resources:
                limits:
                  nvidia.com/gpu: '0'
                requests:
                  cpu: '2'
                  ephemeral-storage: 500M
                  memory: 2Gi
          restartPolicy: OnFailure
          serviceAccountName: uc2-workload-service
  schedule: '*/15 * * * *'
```
